name: Kind BDD test
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      env:
        LOG: console
        
      run: |
        sudo -E ./jx3-kind.sh ci